const data = [
       {"country":"Abkhazia","capital":"Sukhumi","continent":""},
       {"country":"Afghanistan","capital":"Kabul","continent":"Asia"},
       {"country":"Albania","capital":"Tirana","continent":"Europe"},
       {"country":"Algeria","capital":"Algiers", "continent": "Africa" },
       {"country":"American Samoa","capital":"Pago Pago",},
       {"country":"Andorra","capital":"Andorra la Vella","continent":"Europe"},
       {"country":"Angola","capital":"Luanda","continent":"Africa"},
       {"country":"Antigua and Barbuda","capital":"St. John's","continent":"North America"},
       {"country":"Argentina","capital":"Buenos Aires","continent":"South America"},
       {"country":"Armenia","capital":"Yerevan","continent":"Europe"},
       {"country":"Australia","capital":"Canberra","continent":"Oceania"},
       {"country":"Austria","capital":"Vienna","continent":"Europe"},
       {"country":"Azerbaijan","capital":"Baku","continent":"Europe"},
       {"country":"Bahamas","capital":"Nassau","continent":"North America"},
       {"country":"Bahrain","capital":"Manama","continent":"Asia"},
       {"country":"Bangladesh","capital":"Dhaka","continent":"Asia"},
       {"country":"Barbados","capital":"Bridgetown","continent":"North America"},
       {"country":"Belarus","capital":"Minsk","continent":"Europe"},
       {"country":"Belgium","capital":"Brussels","continent":"Europe"},
       {"country":"Belize","capital":"Belmopan","continent":"North America"},
       {"country":"Benin","capital":"Porto-Novo","continent":"Africa"},
       {"country":"Bermuda","capital":"Hamilton","continent":"North America"},
       {"country":"Bhutan","capital":"Thimphu","continent":"Asia"},
       {"country":"Bolivia","capital":"Sucre","continent":"South America"},
       {"country":"Bolivia","capital":"La Paz","continent":"South America"},
       {"country":"Bosnia and Herzegovina","capital":"Sarajevo","continent":"Europe"},
       {"country":"Botswana","capital":"Gaborone","continent":"Africa"},
       {"country":"Brazil","capital":"Brasília","continent":"South America"},
       {"country":"British Virgin Islands","capital":"Road Town","continent":"North America"},
       {"country":"Brunei","capital":"Bandar Seri Begawan","continent":"Asia"},
       {"country":"Bulgaria","capital":"Sofia","continent":"Europe"},
       {"country":"Burkina Faso","capital":"Ouagadougou","continent":"Africa"},
       {"country":"Burundi","capital":"Bujumbura","continent":"Africa"},
       {"country":"Cambodia","capital":"Phnom Penh","continent":"Asia"},
       {"country":"Cameroon","capital":"Yaoundé","continent":"Africa"},
       {"country":"Canada","capital":"Ottawa","continent":"North America"},
       {"country":"Cape Verde","capital":"Praia","continent":"Africa"},
       {"country":"Cayman Islands","capital":"George Town","continent":"North America"},
       {"country":"Central African Republic","capital":"Bangui","continent":"Africa"},
       {"country":"Chad","capital":"N'Djamena","continent":"Africa"},
       {"country":"Chile","capital":"Santiago","continent":"South America"},
       {"country":"China","capital":"Beijing","continent":"Asia"},
       {"country":"Cocos (Keeling) Islands","capital":"West Island","continent":"7"},
       {"country":"Colombia","capital":"Bogotá","continent":"South America"},
       {"country":"Comoros","capital":"Moroni","continent":"Africa"},
       {"country":"Costa Rica","capital":"San José","continent":"North America"},
       {"country":"Croatia","capital":"Zagreb","continent":"Europe"},
       {"country":"Cuba","capital":"Havana","continent":"North America"},
       {"country":"Cyprus","capital":"Nicosia","continent":"Europe"},
       {"country":"Czech Republic","capital":"Prague","continent":"Europe"},
       {"country":"Democratic Republic of the Congo","capital":"Kinshasa","continent":"Africa"},
       {"country":"Denmark","capital":"Copenhagen","continent":"Europe"},
       {"country":"Djibouti","capital":"Djibouti","continent":"Africa"},
       {"country":"Dominica","capital":"Roseau","continent":"North America"},
       {"country":"Dominican Republic","capital":"Santo Domingo","continent":"North America"},
       {"country":"East Timor (Timor-Leste)","capital":"Dili","continent":"Asia"},
       {"country":"Ecuador","capital":"Quito","continent":"South America"},
       {"country":"Egypt","capital":"Cairo","continent":"Africa"},
       {"country":"El Salvador","capital":"San Salvador","continent":"North America"},
       {"country":"Equatorial Guinea","capital":"Malabo","continent":"Africa"},
       {"country":"Eritrea","capital":"Asmara","continent":"Africa"},
       {"country":"Estonia","capital":"Tallinn","continent":"Europe"},
       {"country":"Ethiopia","capital":"Addis Ababa","continent":"Africa"},
       {"country":"Federated States of Micronesia","capital":"Palikir","continent":"Oceania"},
       {"country":"Fiji","capital":"Suva","continent":"Oceania"},
       {"country":"Finland","capital":"Helsinki","continent":"Europe"},
       {"country":"France","capital":"Paris","continent":"Europe"},
       {"country":"French Guiana","capital":"Cayenne","continent":"South America"},
       {"country":"French Polynesia","capital":"Papeete","continent":"Oceania"},
       {"country":"Gabon","capital":"Libreville","continent":"Africa"},
       {"country":"Gambia","capital":"Banjul","continent":"Africa"},
       {"country":"Georgia","capital":"Tbilisi","continent":"Europe"},
       {"country":"Germany","capital":"Berlin","continent":"Europe"},
       {"country":"Ghana","capital":"Accra","continent":"Africa"},
       {"country":"Gibraltar","capital":"Gibraltar","continent":"Europe"},
       {"country":"Greece","capital":"Athens","continent":"Europe"},
       {"country":"Greenland","capital":"Nuuk","continent":"North America"},
       {"country":"Grenada","capital":"St. George's","continent":"North America"},
       {"country":"Guam","capital":"Hagåtña","continent":"Oceania"},
       {"country":"Guatemala","capital":"Guatemala City","continent":"North America"},
       {"country":"Guernsey","capital":"St. Peter Port","continent":"Europe"},
       {"country":"Guinea","capital":"Conakry","continent":"Africa"},
       {"country":"Guinea-Bissau","capital":"Bissau","continent":"Africa"},
       {"country":"Guyana","capital":"Georgetown","continent":"South America"},
       {"country":"Haiti","capital":"Port-au-Prince","continent":"North America"},
       {"country":"Honduras","capital":"Tegucigalpa","continent":"North America"},
       {"country":"Hungary","capital":"Budapest","continent":"Europe"},
       {"country":"Iceland","capital":"Reykjavík","continent":"Europe"},
       {"country":"India","capital":"New Delhi","continent":"Asia"},
       {"country":"Indonesia","capital":"Jakarta","continent":"Asia"},
       {"country":"Iran","capital":"Tehran","continent":"Asia"},
       {"country":"Iraq","capital":"Baghdad","continent":"Asia"},
       {"country":"Ireland","capital":"Dublin","continent":"Europe"},
       {"country":"Isle of Man","capital":"Douglas","continent":"Europe"},
       {"country":"Israel","capital":"Jerusalem","continent":"Asia"},
       {"country":"Italy","capital":"Rome","continent":"Europe"},
       {"country":"Jamaica","capital":"Kingston","continent":"North America"},
       {"country":"Japan","capital":"Tokyo","continent":"Asia"},
       {"country":"Jersey","capital":"St. Helier","continent":"Europe"},
       {"country":"Jordan","capital":"Amman","continent":"Asia"},
       {"country":"Kazakhstan","capital":"Astana","continent":"Asia"},
       {"country":"Kenya","capital":"Nairobi","continent":"Africa"},
       {"country":"Kiribati","capital":"Tarawa","continent":"Oceania"},
       {"country":"Kosovo","capital":"Pristina","continent":"Europe"},
       {"country":"Kuwait","capital":"Kuwait City","continent":"Asia"},
       {"country":"Kyrgyzstan","capital":"Bishkek","continent":"Asia"},
       {"country":"Laos","capital":"Vientiane","continent":"Asia"},
       {"country":"Latvia","capital":"Riga","continent":"Europe"},
       {"country":"Lebanon","capital":"Beirut","continent":"Asia"},
       {"country":"Lesotho","capital":"Maseru","continent":"Africa"},
       {"country":"Liberia","capital":"Monrovia","continent":"Africa"},
       {"country":"Libya","capital":"Tripoli","continent":"Africa"},
       {"country":"Liechtenstein","capital":"Vaduz","continent":"Europe"},
       {"country":"Lithuania","capital":"Vilnius","continent":"Europe"},
       {"country":"Luxembourg","capital":"Luxembourg","continent":"Europe"},
       {"country":"Macedonia","capital":"Skopje","continent":"Europe"},
       {"country":"Madagascar","capital":"Antananarivo","continent":"Africa"},
       {"country":"Malawi","capital":"Lilongwe","continent":"Africa"},
       {"country":"Malaysia","capital":"Kuala Lumpur","continent":"Asia"},
       {"country":"Maldives","capital":"Malé","continent":"Asia"},
       {"country":"Mali","capital":"Bamako","continent":"Africa"},
       {"country":"Malta","capital":"Valletta","continent":"Europe"},
       {"country":"Marshall Islands","capital":"Majuro","continent":"Oceania"},
       {"country":"Mauritania","capital":"Nouakchott","continent":"Africa"},
       {"country":"Mauritius","capital":"Port Louis","continent":"Africa"},
       {"country":"Mexico","capital":"Mexico City","continent":"North America"},
       {"country":"Moldova","capital":"Chisinau","continent":"Europe"},
       {"country":"Monaco","capital":"Monaco","continent":"Europe"},
       {"country":"Mongolia","capital":"Ulaanbaatar","continent":"Asia"},
       {"country":"Montenegro","capital":"Podgorica","continent":"Europe"},
       {"country":"Montserrat","capital":"Plymouth","continent":"North America"},
       {"country":"Morocco","capital":"Rabat","continent":"Africa"},
       {"country":"Mozambique","capital":"Maputo","continent":"Africa"},
       {"country":"Myanmar","capital":"Naypyidaw","continent":"Asia"},
       {"country":"Namibia","capital":"Windhoek","continent":"Africa"},
       {"country":"Nauru","capital":"Yaren","continent":"Oceania"},
       {"country":"Nepal","capital":"Kathmandu","continent":"Asia"},
       {"country":"Netherlands","capital":"Amsterdam","continent":"Europe"},
       {"country":"New Caledonia","capital":"Nouméa","continent":"Oceania"},
       {"country":"New Zealand","capital":"Wellington","continent":"Oceania"},
       {"country":"Nicaragua","capital":"Managua","continent":"North America"},
       {"country":"Niger","capital":"Niamey","continent":"Africa"},
       {"country":"Nigeria","capital":"Abuja","continent":"Africa"},
       {"country":"Niue","capital":"Alofi","continent":"Oceania"},
       {"country":"Norfolk Island","capital":"Kingston","continent":"Oceania"},
       {"country":"North Korea","capital":"Pyongyang","continent":"Asia"},
       {"country":"United Kingdom Northern Ireland","capital":"Belfast","continent":""},
       {"country":"Northern Mariana Islands","capital":"Saipan","continent":""},
       {"country":"Norway","capital":"Oslo","continent":"Europe"},
       {"country":"Oman","capital":"Muscat","continent":"Asia"},
       {"country":"Pakistan","capital":"Islamabad","continent":"Asia"},
       {"country":"Palau","capital":"Ngerulmud","continent":"Oceania"},
       {"country":"Palestine","capital":"Jerusalem","continent":""},
       {"country":"Panama","capital":"Panama City","continent":"North America"},
       {"country":"Papua New Guinea","capital":"Port Moresby","continent":"Oceania"},
       {"country":"Paraguay","capital":"Asunción","continent":"South America"},
       {"country":"Peru","capital":"Lima","continent":"South America"},
       {"country":"Philippines","capital":"Manila","continent":"Asia"},
       {"country":"Pitcairn Islands","capital":"Adamstown","continent":""},
       {"country":"Poland","capital":"Warsaw","continent":"Europe"},
       {"country":"Portugal","capital":"Lisbon","continent":"Europe"},
       {"country":"Puerto Rico","capital":"San Juan","continent":""},
       {"country":"Qatar","capital":"Doha","continent":"Asia"},
       {"country":"Republic of China (Taiwan)","capital":"Taipei","continent":""},
       {"country":"Republic of the Congo","capital":"Brazzaville","continent":""},
       {"country":"Romania","capital":"Bucharest","continent":"Europe"},
       {"country":"Russia","capital":"Moscow","continent":"Asia"},
       {"country":"Rwanda","capital":"Kigali","continent":"Africa"},
       {"country":"Saint Barthélemy","capital":"Gustavia","continent":""},
       {"country":"Saint Helena","capital":"Jamestown","continent":""},
       {"country":"Saint Kitts and Nevis","capital":"Basseterre","continent":"North America"},
       {"country":"Saint Lucia","capital":"Castries","continent":"North America"},
       {"country":"Saint Martin","capital":"Marigot","continent":"7"},
       {"country":"Saint Pierre and Miquelon","capital":"St. Pierre","continent":""},
       {"country":"Saint Vincent and the Grenadines","capital":"Kingstown","continent":"North America"},
       {"country":"Samoa","capital":"Apia","continent":"Oceania"},
       {"country":"San Marino","capital":"San Marino","continent":"Europe"},
       {"country":"Saudi Arabia","capital":"Riyadh","continent":"Asia"},
       {"country":"Scotland","capital":"Edinburgh","continent":""},
       {"country":"Senegal","capital":"Dakar","continent":"Africa"},
       {"country":"Serbia","capital":"Belgrade","continent":"Europe"},
       {"country":"Seychelles","capital":"Victoria","continent":"Africa"},
       {"country":"Sierra Leone","capital":"Freetown","continent":"Africa"},
       {"country":"Singapore","capital":"Singapore","continent":"Asia"},
       {"country":"Sint Maarten","capital":"Philipsburg","continent":"7"},
       {"country":"Slovakia","capital":"Bratislava","continent":"Europe"},
       {"country":"Slovenia","capital":"Ljubljana","continent":"Europe"},
       {"country":"Solomon Islands","capital":"Honiara","continent":"Oceania"},
       {"country":"Somalia","capital":"Mogadishu","continent":"Africa"},
       {"country":"Somaliland","capital":"Hargeisa","continent":""},
       {"country":"South Africa","capital":"Pretoria","continent":"Africa"},
       {"country":"South Georgia and the South Sandwich Islands","capital":"Grytviken","continent":""},
       {"country":"South Korea","capital":"Seoul","continent":"Asia"},
       {"country":"South Ossetia","capital":"Tskhinvali","continent":""},
       {"country":"South Sudan ","capital":"Juba","continent":"Africa"},
       {"country":"Spain","capital":"Madrid","continent":"Europe"},
       {"country":"Sri Lanka","capital":"Sri Jayawardenapura Kotte","continent":"Asia"},
       {"country":"Sudan","capital":"Khartoum","continent":"Africa"},
       {"country":"Suriname","capital":"Paramaribo","continent":"South America"},
       {"country":"Swaziland","capital":"Mbabane","continent":"Africa"},
       {"country":"Sweden","capital":"Stockholm","continent":"Europe"},
       {"country":"Switzerland","capital":"Bern","continent":"Europe"},
       {"country":"Syria","capital":"Damascus","continent":"Asia"},
       {"country":"São Tomé and Príncipe","capital":"São Tomé","continent":""},
       {"country":"Tajikistan","capital":"Dushanbe","continent":"Asia"},
       {"country":"Tanzania","capital":"Dodoma","continent":"Africa"},
       {"country":"Thailand","capital":"Bangkok","continent":"Asia"},
       {"country":"Togo","capital":"Lomé","continent":"Africa"},
       {"country":"Tonga","capital":"Nukuʻalofa","continent":"Oceania"},
       {"country":"Transnistria","capital":"Tiraspol","continent":""},
       {"country":"Trinidad and Tobago","capital":"Port of Spain","continent":"North America"},
       {"country":"Tristan da Cunha","capital":"Edinburgh of the Seven Seas","continent":""},
       {"country":"Tunisia","capital":"Tunis","continent":"Africa"},
       {"country":"Turkey","capital":"Ankara","continent":"Asia"},
       {"country":"Turkmenistan","capital":"Ashgabat","continent":"Asia"},
       {"country":"Turks and Caicos Islands","capital":"Cockburn Town","continent":""},
       {"country":"Tuvalu","capital":"Funafuti","continent":"Oceania"},
       {"country":"Uganda","capital":"Kampala","continent":"Africa"},
       {"country":"Ukraine","capital":"Kiev","continent":"Europe"},
       {"country":"United Arab Emirates","capital":"Abu Dhabi","continent":"Asia"},
       {"country":"United Kingdom; England","capital":"London","continent":"Europe"},
       {"country":"United States","capital":"Washington, D.C.","continent":"North America"},
       {"country":"United States Virgin Islands","capital":"Charlotte Amalie","continent":""},
       {"country":"Uruguay","capital":"Montevideo","continent":"South America"},
       {"country":"Uzbekistan","capital":"Tashkent","continent":"Asia"},
       {"country":"Vanuatu","capital":"Port Vila","continent":"Oceania"},
       {"country":"Vatican City","capital":"Vatican City","continent":"Europe"},
       {"country":"Venezuela","capital":"Caracas","continent":"South America"},
       {"country":"Vietnam","capital":"Hanoi","continent":"Asia"},
       {"country":"Wales","capital":"Cardiff","continent":""},
       {"country":"Wallis and Futuna","capital":"Mata-Utu","continent":""},
       {"country":"Western Sahara","capital":"El Aaiún","continent":""},
       {"country":"Yemen","capital":"Sanaá","continent":"Asia"},
       {"country":"Zambia","capital":"Lusaka","continent":"Africa"},
       {"country":"Zimbabwe","capital":"Harare","continent":"Africa"}
       ]